### PR TITLE
Update to Minecraft 1.20.2

### PR DESCRIPTION
**Pull request by 7coil**
This is a configuration update to Minecraft Normal Edition 1.20.2 - **It does not work with 1.19.3**, which means this PR isn't ready to go in immediately.

This may need a new version to accommodate.

### CODE REVIEW

**Comment by gXLg** [comment]
Does it even make sense to update to 1.20.2? What I mean is - the new villager update fixes the brute forcing. Also, with predefined enchantments from librarians, I would not think, that the 1.20.2 port is just adjusting the version number, I believe the Villager class may have been modified and needs adjustment in the code as well.

**Comment by 7coil** [comment]
The new villager update is not on 1.20.2 (thankfully)

**Comment by gXLg** [comment]
Alright, I will look into it then

**Comment by 7coil** [comment]
Also works with 1.20.3 if you change the fabric.mod.json file :)

**Comment by gXLg** [comment]
It seems, 1.20.2 and Warden are compatible, so I am closing this PR now

**Pull request closed without merging**
