### PR TITLE
Vietnamese

### PR DESCRIPTION
**Pull request by ToanAnh312**
yay now i know how to create a pull
u created a good mod, keep it up xd

### CODE REVIEW

**Comment by gXLg** [comment]
Thanks, I will merge soon. As for your comments:

> the word `custom` in this case isn't easy to translate
Since I don't know Vietnamese, I could only suggest using something like "personal" or "user chosen"

> does `null` need to translate ?
No, this error message is for debug purposes and you would normally not see it in game, except something is very wrong with the game. It is more of a help for me if someone posts an issue, so I can determine, where the issue came from

> the word `menu` in this case isn't easy to translate
You could use something like "configuration". I don't know, if Vietnamese uses borrowed words from English, especially for gamer slang, it could be useful if there is something like this.

My Russian translation also doesn't offer perfect translations and uses a lot of English gamer slang, so it would be fine with me

**Comment by ToanAnh312** [comment]
oh i will do it, we borrow like alot of word and even many word are just get inside our dictionary straight (eg: jeep-"díp", just have the same sound)

**Comment by gXLg** [comment]
Thanks again for your contribution!

**Comment by ToanAnh312** [comment]
np xD

**Comment by ToanAnh312** [comment]
@gXLg ill update the language if there is any changes, notify me if there is :P

**Comment by gXLg** [comment]
Yeah, I wrote about it in the enhancement issue

> @ToanAnh312 I have a new update coming today, it adds a new config.
> 
> In English it will be "Time in seconds to wait for a villager to update its profession before replacing the lectern. Set to 0 to disable."
> 
> Can you help me with a translation into Vietnamese of this one?

**Pull request merged**
